# Generated by Django 6.0.6 on 2026-06-29 20:30

import apps.participantes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True, validators=[apps.participantes.models.validar_cedula_venezolana], verbose_name='C.I.')),
                ('apellidos', models.CharField(max_length=120)),
                ('nombres', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono celular')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('profesion', models.CharField(choices=[('ingeniero_civil', 'Ingeniero civil'), ('ingeniero_estructural', 'Ingeniero estructural'), ('arquitecto', 'Arquitecto'), ('ingeniero_industrial', 'Ingeniero industrial'), ('topografo', 'Topógrafo'), ('estudiante', 'Estudiante'), ('otro', 'Otro')], default='ingeniero_civil', max_length=40, verbose_name='Profesión / ocupación')),
                ('profesion_otro', models.CharField(blank=True, max_length=120, verbose_name='Profesión (otro)')),
                ('procedencia', models.CharField(help_text='Universidad, institución o empresa', max_length=200, verbose_name='Procedencia')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participante',
                'verbose_name_plural': 'participantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
