# Generated by Django 6.0.6 on 2026-06-29 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del edificio')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección / sector')),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Distrito Capital', 'Distrito Capital'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('La Guaira', 'La Guaira'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nueva Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], max_length=50, verbose_name='Estado')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estado_inspeccion', models.CharField(choices=[('pendiente', 'Pendiente de inspección'), ('asignado', 'Asignado a inspector'), ('inspeccionado', 'Inspeccionado')], default='pendiente', max_length=20)),
                ('semaforo', models.CharField(blank=True, choices=[('verde', 'Verde — Habitable'), ('amarillo', 'Amarillo — Acceso restringido'), ('rojo', 'Rojo — No habitable')], max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('inspector_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificaciones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'edificación',
                'verbose_name_plural': 'edificaciones',
                'ordering': ['estado', 'municipio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'En progreso'), ('completada', 'Completada')], default='borrador', max_length=20)),
                ('paso_actual', models.PositiveSmallIntegerField(default=0)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('semaforo', models.CharField(blank=True, choices=[('verde', 'Verde — Habitable'), ('amarillo', 'Amarillo — Acceso restringido'), ('rojo', 'Rojo — No habitable')], max_length=10)),
                ('observaciones_cierre', models.TextField(blank=True)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('edificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='inspecciones.edificacion')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inspección ERD',
                'verbose_name_plural': 'inspecciones ERD',
                'ordering': ['-iniciada_en'],
            },
        ),
    ]
