# Generated by Django 6.0.6 on 2026-06-29 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=200, verbose_name='Responsable por defecto')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'campaña',
                'verbose_name_plural': 'campañas',
                'ordering': ['-activa', '-fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Lugar de inducción')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('responsable_nombre', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='capacitacion.campana')),
            ],
            options={
                'verbose_name': 'sede',
                'verbose_name_plural': 'sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de inducción')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('cupo', models.PositiveIntegerField(default=80)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('responsable_nombre', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='capacitacion.sede')),
            ],
            options={
                'verbose_name': 'sesión',
                'verbose_name_plural': 'sesiones',
                'ordering': ['fecha', 'hora', 'sede__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('asistio', models.BooleanField(default=False)),
                ('certificado_emitido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='participantes.participante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='capacitacion.sesion')),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.UniqueConstraint(fields=('sede', 'fecha', 'hora'), name='uniq_sede_fecha_hora'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('sesion', 'participante'), name='uniq_sesion_participante'),
        ),
    ]
