# Generated by Django 6.0.6 on 2026-06-29 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0002_datos_demo_sedes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='certificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='certificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='encargado_charla',
            field=models.CharField(blank=True, max_length=200, verbose_name='Encargado de la charla (certificado)'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='contenido_induccion',
            field=models.TextField(blank=True, help_text='Temas de la inducción ERD (aparece en el certificado).', verbose_name='Contenido de la charla'),
        ),
    ]
